# The outputs.tf file in Terraform is used to define output values that are generated by your Terraform configuration. Output values allow you to retrieve important information about your infrastructure resources, such as IP addresses or endpoint URLs, after they have been created.

output "tfcloud_workspace_url" {
  description = "Terraform Cloud workspaces"
  value = tfe_workspace.marmite-prod-hcloud.html_url
}